CREATE OR REPLACE FUNCTION public.is_date(s VARCHAR) RETURNS BOOLEAN AS $$
BEGIN
  PERFORM s::date;
  RETURN TRUE;
EXCEPTION WHEN OTHERS THEN
  RETURN FALSE;
END;
$$
STRICT
LANGUAGE plpgsql IMMUTABLE
;
